# 阶段二：寻找函数

## 用（雅各比）迭代法求解 N 元 一次方程组

之前我们求解的都是 3 元一次方程组。如果拟合函数很复杂，有好多元，那我们需要一个更通用的求解方法。

In [ ]:
import numpy as np

In [2]:
# 但是我们展示的时候，还是用之前的那个三元一次方程组
mat_a = np.array(
    [[ 7405.4204,   -182.24994,   608.1     ],
     [ -182.24994,   608.1,        -9.000001],
     [  608.1,        -9.000001,   90.      ]], dtype=np.float32)

mat_b = np.array(
    [[12682.08  ],
     [-2639.4387],
     [ 1227.2014]], dtype=np.float32)

In [3]:
# 雅各比迭代法：
# 对于 A*X = B
# 将 A 分解成对焦矩阵 D 和剩余部分 R
mat_d = np.diag(np.diag(mat_a))
mat_r = mat_a - mat_d

# A*X = B => (D+R)*X = B => DX = B - R*X

# 每次迭代的 X 新值可以写成：
# X_new = inv(D) * (B - R*X_old)

# 雅各比迭代法其实还有更复杂的一步，但是我们省略了，直接获取 inv(D)
# 我们的目的是让大家知道有迭代法这个东西
mat_di = np.linalg.inv(mat_d)

In [4]:
np.matmul(mat_di, mat_d)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [5]:
# 我们做 100 次迭代
iter_max = 100

# X 的初始值随机生成
x_0 = np.random.rand(3,1)
x_k = x_0
x_kp = x_0

print(x_0)

[[0.04014376]
 [0.93205122]
 [0.58665674]]


In [6]:
for _ in range(iter_max):
    x_kp = np.matmul(mat_di, (mat_b - np.matmul(mat_r, x_k)))
    x_k = x_kp
    
print(x_kp)

[[ 1.18779547]
 [-3.90723458]
 [ 5.21931015]]


In [7]:
print('Checking the ground truth of [a,b,c]')
np.array([1.2, -3.7, 4.9]).astype(np.float64)

Checking the ground truth of [a,b,c]


array([ 1.2, -3.7,  4.9])

In [8]:
print('Checking the result from direct linear solver')
np.array([1.24553038, -3.65123161,  5.01053186]).astype(np.float64)

Checking the result from direct linear solver


array([ 1.24553038, -3.65123161,  5.01053186])